import PhotoDiana from '../images/players/1-diana.jpg';
import PhotoLara from '../images/players/4-lara.jpg';
import PhotoMerida from '../images/players/9-merida.jpg';
import PhotoLisa from '../images/players/13-lisa.jpg';
import PhotoLisbeth from '../images/players/24-lisbeth.jpg';
import PhotoAlice from '../images/players/37-alice.jpg';

export const Squad = [
  {
    shirt     : 1,
    name      : 'Diana',
    position  : 'Portera',
    cod       : 'GK',
    city      : 'Themyscira',
    country   : 'eu',
    since     : 2015,
    photo     : PhotoDiana,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 4,
    name      : 'Lara',
    position  : 'Defensa Central',
    cod       : 'FB rightFocus',
    city      : 'Wimbledom',
    country   : 'gb',
    since     : 2018,
    photo     : PhotoLara,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 24,
    name      : 'Lisbeth',
    position  : 'Banda Derecha',
    cod       : 'RM',
    city      : 'Stocolm',
    country   : 'se',
    since     : 2014,
    photo     : PhotoLisbeth,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 9,
    name      : 'Merida',
    position  : 'Delantera',
    cod       : 'ST',
    city      : 'DunBroch',
    country   : 'gb',
    since     : 2016,
    photo     : PhotoMerida,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 13,
    name      : 'Lisa',
    position  : 'Medio Izquierda / Central',
    cod       : 'MF leftFocus',
    city      : 'Springfield',
    country   : 'us',
    since     : 2018,
    photo     : PhotoLisa,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 37,
    name      : 'Alice',
    position  : 'Medio Central',
    cod       : 'MF',
    city      : 'Raccooncity',
    country   : 'us',
    since     : 2017,
    photo     : PhotoAlice,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
];
