import PhotoDiana from '../images/players/1-diana.jpg';
import PhotoLara from '../images/players/4-lara.jpg';
import PhotoMerida from '../images/players/9-merida.jpg';
import PhotoLisa from '../images/players/13-lisa.jpg';
import PhotoLisbeth from '../images/players/24-lisbeth.jpg';
import PhotoAlice from '../images/players/37-alice.jpg';

export const SQUAD = [
  {
    shirt     : 1,
    name      : 'Sheila Camacho',
    shortname : 'Camacho',
    position  : 'Portera',
    cod       : 'GK',
    city      : 'Themyscira',
    country   : 'es',
    since     : 2015,
    photo     : PhotoDiana,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 2,
    name      : 'Annelies Romjin',
    shortname : 'Lies',
    position  : 'Defensa Central',
    cod       : 'FB rightFocus',
    city      : 'Wimbledom',
    country   : 'nl',
    since     : 2018,
    photo     : PhotoLara,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 3,
    name      : 'Mariki',
    shortname : 'Mariki',
    position  : 'Banda Derecha',
    cod       : 'RM',
    city      : 'Stocolm',
    country   : 'es',
    since     : 2014,
    photo     : PhotoLisbeth,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 5,
    name      : 'Ana Torres',
    shortname : 'Ana',
    position  : 'Delantera',
    cod       : 'ST',
    city      : 'DunBroch',
    country   : 'es',
    since     : 2016,
    photo     : PhotoMerida,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 6,
    name      : 'Adriana',
    shortname : 'Adri',
    position  : 'Medio Izquierda / Central',
    cod       : 'MF leftFocus',
    city      : 'Springfield',
    country   : 'es',
    since     : 2018,
    photo     : PhotoLisa,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 7,
    name      : 'Sheila',
    shortname : 'Shei',
    position  : 'Medio Central',
    cod       : 'MF',
    city      : 'Raccoon City',
    country   : 'es',
    since     : 2017,
    photo     : PhotoAlice,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 8,
    name      : 'Anna Branco',
    shortname : 'Anna',
    position  : 'Delantera',
    cod       : 'ST',
    city      : 'Rio de Janeiro',
    country   : 'br',
    since     : 2015,
    photo     : PhotoDiana,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 9,
    name      : 'Beatriz',
    shortname : 'Bea',
    position  : 'Defensa Central',
    cod       : 'FB rightFocus',
    city      : 'Wimbledom',
    country   : 'es',
    since     : 2018,
    photo     : PhotoLara,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 10,
    name      : 'Laura',
    shortname : 'Laura',
    position  : 'Banda Derecha',
    cod       : 'RM',
    city      : 'Stocolm',
    country   : 'es',
    since     : 2014,
    photo     : PhotoLisbeth,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 11,
    name      : 'Raquel Herzog',
    shortname : 'Herzog',
    position  : 'Delantera',
    cod       : 'ST',
    city      : 'DunBroch',
    country   : 'es',
    since     : 2016,
    photo     : PhotoMerida,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 12,
    name      : 'Encarnación',
    shortname : 'Encarni',
    position  : 'Medio Izquierda / Central',
    cod       : 'MF leftFocus',
    city      : 'Springfield',
    country   : 'es',
    since     : 2018,
    photo     : PhotoLisa,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 13,
    name      : 'Ilse',
    shortname : 'Ilse',
    position  : 'Medio Central',
    cod       : 'MF',
    city      : 'Raccoon City',
    country   : 'nl',
    since     : 2017,
    photo     : PhotoAlice,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 14,
    name      : 'Camille',
    shortname : 'Camille',
    position  : 'Portera',
    cod       : 'GK',
    city      : 'Themyscira',
    country   : 'fr',
    since     : 2015,
    photo     : PhotoDiana,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 15,
    name      : 'Mary',
    shortname : 'Mary',
    position  : 'Defensa Central',
    cod       : 'FB rightFocus',
    city      : 'Wimbledom',
    country   : 'es',
    since     : 2018,
    photo     : PhotoLara,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 16,
    name      : 'Beatriz Herzog',
    shortname : 'Beah',
    position  : 'Banda Derecha',
    cod       : 'RM',
    city      : 'Stocolm',
    country   : 'es',
    since     : 2014,
    photo     : PhotoLisbeth,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 19,
    name      : 'Estefanía',
    shortname : 'Estefi',
    position  : 'Delantera',
    cod       : 'ST',
    city      : 'DunBroch',
    country   : 'es',
    since     : 2016,
    photo     : PhotoMerida,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 21,
    name      : 'Raquel Escudero',
    shortname : 'Escudero',
    position  : 'Medio Izquierda / Central',
    cod       : 'MF leftFocus',
    city      : 'Springfield',
    country   : 'es',
    since     : 2018,
    photo     : PhotoLisa,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
  {
    shirt     : 37,
    name      : 'Raquel Vega',
    shortname : 'Vega',
    position  : 'Medio Central',
    cod       : 'MF',
    city      : 'Raccoon City',
    country   : 'es',
    since     : 2017,
    photo     : PhotoAlice,
    twitter   : '',
    facebook  : '',
    instagram : '',
  },
];
